### ISSUE TITLE
Unable to compile using MacOS (M1 arm chip)

### ISSUE THREAD

**Issue by Singha360** [NodeppOficial/nodepp#1]
I am unable to compile using gcc on macos. I copy paste the hello world example in the readme and this is what I get:

```
error: #error "This OS Does not support sleep.h"
   22 |     #error "This OS Does not support sleep.h"
      |      ^~~~~
```
```
error: #error "This OS Does not support env.h"
   22 |     #error "This OS Does not support env.h"
      |      ^~~~~
In file included from /Users/xo/.local/include/nodepp/import.h:44:
/Users/xo/.local/include/nodepp/task.h: In function 'int nodepp::process::next()':
/Users/xo/.local/include/nodepp/task.h:185:23: error: 'delay' is not a member of 'nodepp::process'
  185 |              process::delay( TIMEOUT );
      |                       ^~~~~
```
```
error: 'delay' is not a member of 'nodepp::process'
  188 |         if( x == 0 ){ process::delay( TIMEOUT ); coGoto(0); }
      |                                ^~~~~
```
```
error: 'nodepp::process::env' has not been declared
   36 |                      process::env::set( x.first, x.second );
      |                               ^~~
```

**Comment by Singha360** [comment]
this is in `import.h`

<img width="605" alt="image" src="https://github.com/NodeppOficial/nodepp/assets/35334787/b03a49f8-c846-4a91-9de0-b6394f1c52c8">

**Comment by Singha360** [comment]
Okay I should've been more careful before posting this... 😅

So I rewrote like so:
```cpp
#define _KERNEL NODEPP_KERNEL_POSIX
#include <nodepp/nodepp.h>

using namespace nodepp;

void onMain()
{
    console::log("Hello World!");
}
```

And now I get this:
```
/Users/xo/.local/include/nodepp/posix/env.cpp: In function 'int nodepp::{anonymous}::CLEAR()':
/Users/xo/.local/include/nodepp/posix/env.cpp:25:25: error: 'clearenv' was not declared in this scope; did you mean 'clearerr'?
   25 |     int CLEAR(){ return clearenv(); }
      |                         ^~~~~~~~
      |                         clearerr
```

**Comment by Singha360** [comment]
https://github.com/facebook/folly/issues/567

Might be of help, I will be honest I know very little of working under C++ so I am just testing things out and reporting what I am seeing for now. I think this project is interesting and hope this goes bigger.

**Comment by Singha360** [comment]
[Here it says this:](https://www.gnu.org/software/gnulib/manual/html_node/clearenv.html)

This function is missing on some platforms: macOS 11.1, FreeBSD 13.2, NetBSD 10.0, OpenBSD 6.7, Minix 3.1.8, Solaris 10, Cygwin 2.9, mingw, MSVC 14.

**Comment by EDBCREPO** [comment]
Hey, @Singha360 thank you for being interested in this project. 

Ok, the truth is that I've never tried NodePP on MacOS or FreeBSD, so I knew things like this would happen.

So, I have made some changes to the macros and also commented out the clearenv() function.

With these changes, I think, it should work. Could you try it again and tell me if it works?

**Comment by Singha360** [comment]
Okay currently at work so I'll test it out later in the evening

**Comment by Singha360** [comment]
@EDBCREPO It is working now!

Thank you!

I'll play around with it and see if I find anything else and open a new issues. Going to close this one.
