### ISSUE TITLE
Object size is always 0

### ISSUE THREAD

**Issue by Singha360** [NodeppOficial/nodepp#2]
```cpp
#define _KERNEL NODEPP_KERNEL_POSIX
#include <nodepp/nodepp.h>
#include <nodepp/object.h>

using namespace nodepp;

void onMain()
{
    object_t ppt({{"name", "Bob"}, {"age", 25}});
    ppt["myKey"] = "myValue";

    console::log(ppt.size());
}
```

For some reason this always returns to me 0 despite holding items inside the object.

**Comment by EDBCREPO** [comment]
I think is solved it. Thanks 👍

Could you try to compile without this macro?

#define _KERNEL NODEPP_KERNEL_POSIX

**Comment by Singha360** [comment]
Perfect, it's working and no need for the macro
