### ISSUE TITLE
build error with Include nodepp in a class

### ISSUE THREAD

**Issue by trolly98** [NodeppOficial/nodepp#5]
Hi, great projects.
I'm trying to implement it in my class in c++:

testclass.h
```
#pragma once
#include <nodepp/nodepp.h>
class TestClass
{
public:
TestClass();
}
```

testclass.cpp
```
#include "testclass.h"
TestClass::TestClass() {}
```

main.cpp
```
#include "testclass.h"
int main()
{
Testclass t();
return 0;
}
```

CMakeLists.txt

```
cmake_minimum_required(VERSION 3.16)
project(test_cpp LANGUAGES CXX)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/nodepp/include)
add_executable(test_cpp
main.cpp
testclass.h
testclass.cpp
)
```

With this configuration compilation goes wrong with a lot of errors.
If you try it you can reproduce that errors.
Otherwise I could copy my errors here.
Let me know!
Thanks

**Comment by EDBCREPO** [comment]
## CMakeLists.txt
```bash
cmake_minimum_required(VERSION 3.16)
project( test_cpp LANGUAGES CXX )
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/nodepp/include)
add_executable(
    test_cpp
    main.cpp
    testclass.h
    testclass.cpp
)
```

## testclass.h
```cpp
#ifndef TESTCLASS_H
#define TESTCLASS_H

class TestClass { public:
    
   ~TestClass();
    TestClass();

};

#include "testclass.cpp"
#endif
```

## testclass.cpp
```cpp
#ifdef TESTCLASS_H

TestClass::TestClass() {
    console::log( "TestClass Constructor" );
}

TestClass::~TestClass() {
    console::log( "TestClass Destructor" );
}

#endif
```

## main.cpp
```cpp
#include <nodepp/nodepp.h>

using namespace nodepp;

#include "testclass.h"

void onMain() {

    TestClass t;

}
```

---

Ok, Nodepp was designed to be imported at the beginning of the code using:
`#include <nodepp/nodepp.h>` and `using namespace nodepp;` to get access the Nodepp's features.

Then, you have to use `void onMain()` instead of `int main()`, because Nodepp internally initializes an Event Loop that makes it C++ possible to handle asynchronous tasks. But if you don't like this method, there's an alternative using `process::start()` and `process::stop()`.

---

```cpp
#include <nodepp/nodepp.h>

using namespace nodepp;

void onMain() { /*Yout Code*/ }
```

Or

```cpp
#include <nodepp/nodepp.h>

using namespace nodepp;

int main( int argc, char** args ){
    process::start( argc, args );
    /*Yout Code*/ 
    process::stop();
}
```

**Comment by trolly98** [comment]
Yeah thanks.
There are two things I didn't understand.
- Why are you include ".cpp" file in header file?
- How can I define a nodepp::event_t<> like a member of my class?

Thanks!

**Comment by EDBCREPO** [comment]
Now, about creating events as class members in your Nodepp's applications. I've got some tips for you.
- Remember to use `ptr_t` inside your class, to make it async-task and worker friendly.
- Remember to use `type::bind(this)` to avoid self context leak.

Ok, `ptr_t` objects are just smart pointers, they are useful to share information between processes. Meanwhile `type::bind()` is just a function that returns `ptr_t` objects, but `type::bind(this)` is useful when you try to use `this` inside an asyn-task or a worker.

## testclass.h
```cpp
#ifndef TESTCLASS_H
#define TESTCLASS_H

class TestClass {
protected:

    // Store the variables you want to share among async tasks or multithreaded tasks ( workers )
    struct NODE {
        int var = 10; // <- here is your variable but you can declare more
    };  ptr_t<NODE> obj;

public:

    event_t onEvent; // <- event_t is async | worker friendly
    
   ~TestClass();
    TestClass();

};

#include "testclass.cpp"
#endif
```

## testclass.cpp
```cpp
#ifdef TESTCLASS_H

TestClass::TestClass() { 
    obj = new TestClass::NODE();    // <- remember initialize the shared variables
    auto self = type::bind( this ); // <- remember create a self shared context

    onEvent.on([=](){

        // <- modify your internal variables using self instead of this
        while( self->obj->var --> 0 ){
        // <- read your internal variable using self instead of this
            console::log( "Hello World", self->obj->var );
        }

    });

  //onEvent.once( ... ) let you create one time emitale event.

    console::log( "TestClass Constructor" );

    onEvent.emit(); // <- to emit the events
    
}

TestClass::~TestClass() {
    // <- execute the destructor only once the shared variables aren't used anymore
    if( obj.count() > 1 ){ return; } console::log( "TestClass Destructor" );
}

#endif
```

NOTE: all Nodepp's objects are async | worker friendly, but if you want to create one from scratch, these tips will make your life easier.
